"""OAuth for the Google Drive connector — host-side only (see README.md).

Read-only scope: this connector only ever reads a document's content and
metadata, never writes to Drive. The OAuth client secret and the resulting
user token both live under ~/.longbrain (never inside Qdrant or the
container), consistent with how ingest_watcher.py already keeps its own
host-side state under the user's home directory.
"""

from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow

SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]

LONGBRAIN_HOME = Path.home() / ".longbrain"
CLIENT_SECRET_FILE = LONGBRAIN_HOME / "google_oauth_client.json"
TOKEN_FILE = LONGBRAIN_HOME / "google_drive_token.json"


def get_credentials() -> Credentials:
    """Cached OAuth credentials, refreshing or re-authorizing as needed.

    First call opens a browser for the user to grant access (InstalledAppFlow
    local-server redirect); every call after that reuses the cached token
    from TOKEN_FILE, silently refreshing it when expired. Raises
    FileNotFoundError with a setup pointer if CLIENT_SECRET_FILE is missing —
    that file must come from the user's own Google Cloud OAuth client (see
    README.md); it cannot be generated by this connector.
    """
    creds = None
    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    if creds and creds.valid:
        return creds

    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        if not CLIENT_SECRET_FILE.exists():
            raise FileNotFoundError(
                f"Missing {CLIENT_SECRET_FILE}. Create a Google Cloud OAuth "
                "2.0 Client ID (Desktop app type), download its JSON, and "
                "save it at this exact path — see connectors/google_drive/"
                "README.md for the step-by-step Google Cloud Console setup."
            )
        flow = InstalledAppFlow.from_client_secrets_file(
            str(CLIENT_SECRET_FILE), SCOPES
        )
        creds = flow.run_local_server(port=0)

    LONGBRAIN_HOME.mkdir(parents=True, exist_ok=True)
    TOKEN_FILE.write_text(creds.to_json())
    # Cached credentials are as good as a login session — keep them
    # user-readable only.
    TOKEN_FILE.chmod(0o600)
    return creds
